// ─── Domain Error Codes ─────────────────────────────────────────
// String constants for all domain-level errors. Used in DomainError
// on the API and parsed on the frontend for i18n / field mapping.

export const ERRORS = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Generic
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Catalogue
  DISH_NOT_FOUND: 'DISH_NOT_FOUND',
  DISH_INACTIVE: 'DISH_INACTIVE',
  OPTION_NOT_FOUND: 'OPTION_NOT_FOUND',
  OPTION_INACTIVE: 'OPTION_INACTIVE',
  OPTION_GROUP_NOT_FOUND: 'OPTION_GROUP_NOT_FOUND',

  // Pricing
  TIER_NOT_FOUND: 'TIER_NOT_FOUND',
  TIER_CYCLE: 'TIER_CYCLE',
  TIER_CHAIN_TOO_DEEP: 'TIER_CHAIN_TOO_DEEP',
  PRICE_NOT_SET: 'PRICE_NOT_SET',

  // Companies
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  DOMAIN_TAKEN: 'DOMAIN_TAKEN',
  DOMAIN_PUBLIC: 'DOMAIN_PUBLIC',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',

  // Employees
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_HAS_OPEN_ORDERS: 'EMPLOYEE_HAS_OPEN_ORDERS',

  // Orders
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_LOCKED: 'ORDER_LOCKED',
  ORDER_NOT_EDITABLE: 'ORDER_NOT_EDITABLE',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  ORDER_ALREADY_INVOICED: 'ORDER_ALREADY_INVOICED',
  INVALID_DELIVERY_DATE: 'INVALID_DELIVERY_DATE',
  DELIVERY_DATE_NOT_WORKING: 'DELIVERY_DATE_NOT_WORKING',
  DELIVERY_DATE_HOLIDAY: 'DELIVERY_DATE_HOLIDAY',
  DELIVERY_DATE_PAST: 'DELIVERY_DATE_PAST',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  COMBINATION_SUM_MISMATCH: 'COMBINATION_SUM_MISMATCH',
  COMBINATION_DUPLICATE_SIGNATURE: 'COMBINATION_DUPLICATE_SIGNATURE',
  REQUIRED_GROUP_MISSING: 'REQUIRED_GROUP_MISSING',
  INVALID_OPTION_SELECTION: 'INVALID_OPTION_SELECTION',
  MIN_ORDER_QTY: 'MIN_ORDER_QTY',
  NO_LINES: 'NO_LINES',
  VERSION_CONFLICT: 'VERSION_CONFLICT',

  // Cut-off
  CUTOFF_ALREADY_RUNNING: 'CUTOFF_ALREADY_RUNNING',

  // Kitchen
  UNIT_ALREADY_STARTED: 'UNIT_ALREADY_STARTED',
  UNIT_ALREADY_DONE: 'UNIT_ALREADY_DONE',
  ORDER_NOT_CONFIRMED: 'ORDER_NOT_CONFIRMED',

  // Dispatch
  DROP_NOT_FOUND: 'DROP_NOT_FOUND',
  DROP_NOT_KITCHEN_READY: 'DROP_NOT_KITCHEN_READY',
  DROP_NOT_DISPATCH_READY: 'DROP_NOT_DISPATCH_READY',
  DROP_NO_DRIVER: 'DROP_NO_DRIVER',
  DROP_NOT_OUT_FOR_DELIVERY: 'DROP_NOT_OUT_FOR_DELIVERY',
  DROP_ALREADY_DELIVERED: 'DROP_ALREADY_DELIVERED',

  // Billing
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  ORDERS_NOT_BILLABLE: 'ORDERS_NOT_BILLABLE',

  // Settings
  SETTING_NOT_FOUND: 'SETTING_NOT_FOUND',
  INVALID_SETTING_VALUE: 'INVALID_SETTING_VALUE',
} as const;

export type ErrorCode = (typeof ERRORS)[keyof typeof ERRORS];
